// <auto-generated />
using System;
using AppCase.EFDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppCase.EFDataAccess.Migrations
{
    [DbContext(typeof(EFDatabaseContext))]
    partial class EFDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppCase.Core.Entities.BookTrace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("BookCheckoutDate")
                        .HasColumnName("BOOK_CHECKOUT_DATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BookReturnDate")
                        .HasColumnName("BOOK_RETURN_DATE")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Calculated")
                        .HasColumnName("CALCULATED")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CountryId")
                        .HasColumnName("COUNTRY_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("BOOK_TRACES");
                });

            modelBuilder.Entity("AppCase.Core.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnName("CALTURE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weekends")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("COUNTRIES");
                });

            modelBuilder.Entity("AppCase.Core.Entities.CountryHoliday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CountryId")
                        .HasColumnName("COUNTRY_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Holiday")
                        .HasColumnName("HOLIDAY")
                        .HasColumnType("datetime2");

                    b.Property<int>("HolidayType")
                        .HasColumnName("HOLIDAY_TYPE")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("COUNTRY_HOLIDAYS");
                });

            modelBuilder.Entity("AppCase.Core.Entities.BookTrace", b =>
                {
                    b.HasOne("AppCase.Core.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCase.Core.Entities.CountryHoliday", b =>
                {
                    b.HasOne("AppCase.Core.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
